Repository Codeit-MovieGlass/MovieGlass_FE, pull requests merged in 2025-01, with the labels that each got.

#2 Chore: 프로젝트 초기 세팅
  .gitignore
  .prettierrc
  eslint.config.js
  index.html
  jsconfig.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/layout/Layout.jsx
  src/main.jsx
  src/pages/Home/Home.jsx
  vite.config.js
  yarn.lock
Labels: setup

#4 Style: 글로벌 스타일 가이드 설정 및 스타일 초기 세팅
  jsconfig.json
  package.json
  src/main.jsx
  src/styles/global/_base.scss
  src/styles/global/_fonts.scss
  src/styles/global/_normalize.scss
  src/styles/global/_responsive.scss
  src/styles/global/_variables.scss
  src/styles/global/global.scss
  src/styles/theme/colors.js
  src/styles/theme/theme.js
  src/styles/theme/typography.js
  src/utils/pxToRem.js
  theme.d.ts
  vite.config.js
  yarn.lock
Labels: styling, setup

#6 Feat: Header 컴포넌트 UI 구현
  index.html
  jsconfig.json
  package.json
  public/movieglass.svg
  public/vite.svg
  src/assets/svgs/Header/DefaultProfile.svg
  src/assets/svgs/Header/Logo_symbol.svg
  src/assets/svgs/Header/Logo_typo.svg
  src/assets/svgs/Header/Logo_typo_serif.svg
  src/assets/svgs/Header/Magnifier.svg
  src/assets/svgs/Header/Magnifier_solo.svg
  src/components/UserMenuDropdown/UserMenuDropdown.jsx
  src/components/UserMenuDropdown/UserMenuDropdown.styled.js
  src/icons/Logo.js
  src/icons/Magnifier.js
  src/layout/Header/Header.jsx
  src/layout/Header/Header.styled.js
  src/layout/Header/SearchBar/SearchBar.jsx
  src/layout/Header/SearchBar/SearchBar.styled.js
  src/layout/Layout.jsx
  src/pages/Home/Home.jsx
  src/styles/global/_base.scss
  src/styles/global/_fonts.scss
  src/styles/global/_normalize.scss
  vite.config.js
  yarn.lock
Labels: feature, UI

#8 Feat: Home 페이지 내 컴포넌트 UI 구현
  README.md
  public/emoji/happy.svg
  public/emoji/love.svg
  public/emoji/sad.svg
  public/emoji/soso.svg
  public/emoji/tough.svg
  src/assets/svgs/Header/DefaultProfile.svg
  src/assets/svgs/icons/arrow.svg
  src/assets/svgs/icons/emojiBalloon.svg
  src/assets/svgs/icons/shuffle.svg
  src/assets/svgs/icons/textBalloon.svg
  src/components/Balloon/Balloon.styled.js
  src/components/Balloon/EmojiBalloon.jsx
  src/components/Balloon/TextBalloon.jsx
  src/components/MovieIntroBox/MovieIntroBox.jsx
  src/components/MovieIntroBox/MovieIntroBox.styled.js
  src/components/Rating/Rating.jsx
  src/components/Rating/Rating.styled.js
  src/components/Rating/Star.jsx
  src/icons/Arrow.js
  src/icons/Balloon.js
  src/icons/Shuffle.js
  src/layout/Header/Header.jsx
  src/layout/Header/Header.styled.js
  src/styles/global/_base.scss
  src/styles/theme/typography.js
Labels: UI, components

#11 Fix: Upgrade Vite to 6.0.11
  yarn.lock
Labels: bug, security

#12 feat(animation): Loading 애니메이션 컴포넌트 구현 (#10)
  src/components/Loading/Loading.jsx
  src/components/Loading/Loading.styled.js
Labels: components

#14 Feat: 영화 상세 모달 내 컴포넌트 UI 구현
  package.json
  public/OTT/coupangplay.png
  public/OTT/disneyplus.png
  public/OTT/moreOtt.svg
  public/OTT/netflix.png
  public/OTT/tving.png
  public/OTT/watcha.png
  public/star/star-input_empty.svg
  public/star/star-input_filled.svg
  src/assets/svgs/icons/eye.svg
  src/components/Comment/Read/CommentList.jsx
  src/components/Comment/Read/ReadComment.jsx
  src/components/Comment/Read/ReadComment.styled.js
  src/components/OTTLink/MoreModal.jsx
  src/components/OTTLink/MoreModal.styled.js
  src/components/OTTLink/OTTLink.jsx
  src/components/OTTLink/OTTLink.styled.js
  src/components/RatingInput/RatingInput.jsx
  src/components/RatingInput/RatingInput.styled.js
  src/components/SpoilerToggle/SpoilerToggle.jsx
  src/components/SpoilerToggle/SpoilerToggle.styled.js
  src/components/WriteReview/WriteReview.jsx
  src/components/WriteReview/WriteReview.styled.js
  src/icons/Eye.js
  src/icons/Logo.js
  src/styles/global/_base.scss
  yarn.lock
Labels: UI, components

#21 Feat: 영화 상세 모달 내 컴포넌트 UI 구현 (2)
  src/assets/svgs/icons/dropdown-arrow.svg
  src/assets/svgs/icons/heart.svg
  src/assets/svgs/icons/pencil.svg
  src/assets/svgs/icons/pin.svg
  src/assets/svgs/icons/trash.svg
  src/components/Comment/Read/CommentList.jsx
  src/components/Comment/Read/ReadComment.jsx
  src/components/Like/Like.jsx
  src/components/Like/Like.styled.js
  src/components/Review/MyReview/MyReview.jsx
  src/components/Review/MyReview/MyReview.styled.js
  src/components/Review/Review.jsx
  src/components/Review/Review.styled.js
  src/components/Review/ReviewList.jsx
  src/components/Review/WriteReview/WriteReview.jsx
  src/components/Review/WriteReview/WriteReview.styled.js
  src/components/ViewCount/Dropdown/ViewCountDropdown.jsx
  src/components/ViewCount/Dropdown/ViewCountDropdown.styled.js
  src/components/ViewCount/ViewCount.jsx
  src/components/ViewCount/ViewCount.styled.js
  src/icons/Arrow.js
  src/icons/EditDelete.js
  src/icons/Eye.js
  src/icons/Pin.js
Labels: UI, components

#16 Feat: 로그인 및 회원가입 UI 구현
  package.json
  src/App.jsx
  src/assets/svgs/icons/arrow_right.svg
  src/assets/svgs/icons/check_icon.svg
  src/assets/svgs/icons/eyelnvisible.svg
  src/assets/svgs/icons/google_logo.svg
  src/assets/svgs/icons/kakao_logo.svg
  src/auth/auth.js
  src/icons/Logo.js
  src/layout/Layout.jsx
  src/layout/Layout.styled.js
  src/layout/OnBoarding/OnBoardingLayout.jsx
  src/layout/OnBoarding/OnBoardingLayout.styled.js
  src/layout/OnBoarding/Welcome/Welcome.jsx
  src/layout/OnBoarding/Welcome/Welcome.styled.js
  src/pages/Onboarding/Login/Login.jsx
  src/pages/Onboarding/Login/Login.styled.js
  src/pages/Onboarding/SignUp/SignUp.jsx
  src/pages/Onboarding/SignUp/SignUp.styled.js
  src/styles/global/_base.scss
  yarn.lock
Labels: UI, components
